daily
rotate 0
size 1M
create
compress
include /etc/logrotate.d
/var/log/wtmp {
    missingok
    monthly
    create 0664 root utmp
    rotate 0
}
/var/log/btmp {
    missingok
    monthly
    create 0660 root utmp
    rotate 0
}
