authselectmode require
# maxpoll for faster selection of reachable clock source after
# the current source becomes unreachable (from chrony FAQ 3.5)
server time.cloudflare.com iburst nts maxpoll 8
server nts.sth1.ntp.se iburst nts maxpoll 8
server nts.sth2.ntp.se iburst nts maxpoll 8
# Disable checking of certificate times on first clock update as
# as we don't have a RTC.
nocerttimecheck 1
keyfile /etc/chrony/chrony.keys
driftfile /data/chrony/chrony.drift
ntsdumpdir /data/chrony
logdir /var/log/chrony
maxupdateskew 100.0
makestep 1 3
leapsectz right/UTC
manual
# maxclockerror for faster selection of reachable clock source after
# the current source becomes unreachable (from chrony FAQ 3.5)
maxclockerror 10
